FROM node:10.11.0

# WORKDIR /usr/src
# WORKDIR /

COPY . .

RUN npm ci

ENV NODE_PATH=./
ENV UI_ROOT=http://localhost:8080
ENV EGO_API_ROOT=http://localhost:9000
ENV EGO_CLIENT_ID=
ENV GATEWAY_API_ROOT=
ENV BROWSERSTACK_ACCESS_KEY=
ENV BROWSERSTACK_USER=
ENV BROWSERSTACK_API_ROOT=https://api.browserstack.com/automate
ENV BROWSERSTACK_SELENIUM_HOST=hub-cloud.browserstack.com
ENV BROWSERSTACK_PROJECT_NAME=ci_test

# Test User Details
ENV LOGIN_USERID_DCCADMIN=
ENV LOGIN_USERPASS_DCCADMIN=
ENV LOGIN_USERID_PROGRAM_ADMIN_MULTI=
ENV LOGIN_USERPASS_PROGRAM_ADMIN_MULTI=
ENV LOGIN_USERID_PROGRAM_ADMIN_SINGLE=
ENV LOGIN_USERPASS_PROGRAM_ADMIN_SINGLE=
ENV TOKEN_DCCADMIN=
ENV TOKEN_PROGRAM_ADMIN_MULTI=
ENV TOKEN_DCCADMIN_PROGRAM_ADMIN_SINGLE=

CMD [ "npm", "run", "browserstack" ]